# Configurations used when running emmocheck from the ci_emmocheck workflow
#skip:
#  - test_description

test_description:
  skipmodules:
    - manufacturing
    - metrology
    - isq
    - materials
    - math
    - models
    - chemistry
    - computerscience
    - perceptual
    - mereocausality-full
    - standardmodel-full

test_namespace:
  exceptions:
    - manufacturing.EngineeredMaterial

test_quantity_dimension:
  exceptions:
    - emmo.ModelledQuantitativeProperty
    - emmo.MeasuredQuantitativeProperty
    - emmo.ConventionalQuantitativeProperty
    - emmo.QuantitativeProperty
    - emmo.Quantity
    - emmo.OrdinalQuantity
    - emmo.BaseQuantity
    - emmo.PhysicalConstant
    - emmo.PhysicalQuantity
    - emmo.ExactConstant
    - emmo.MeasuredConstant
    - emmo.DerivedQuantity
    - emmo.ISQBaseQuantity
    - emmo.InternationalSystemOfQuantity
    - emmo.ISQDerivedQuantity
    - emmo.SIExactConstant

test_class_label:
  exceptions:
    - pH
    - 3DPrinting

test_unit_dimension:
  exceptions:
    - emmo.BaseUnit
    - emmo.DerivedUnit
    - emmo.MultipleUnit
    - emmo.NonPrefixedUnit
    - emmo.NonSISpecialUnit
    - emmo.NonSIUnit
    - emmo.OffSystemUnit
    - emmo.PrefixedUnit
    - emmo.SIAcceptedDerivedUnit
    - emmo.SIAcceptedPrefixedUnit
    - emmo.SIBaseUnit
    - emmo.SICoherentDerivedUnit
    - emmo.SICoherentUnit
    - emmo.SIDerivedUnit
    - emmo.SINonCoherentDerivedUnit
    - emmo.SIPrefixedUnit
    - emmo.SISpecialUnit
    - emmo.SIUnit
    - emmo.SIUnitSymbol
    - emmo.SpecialUnit
    - emmo.SubMultipleUnit
    - emmo.UnitSymbol

test_number_of_labels:
  exceptions:
    - 0.1.Person  # foaf:Person
    - 0.1.mbox  # foaf:mbox
