# Input file for testing redirections
#
# These redirections can be tested using the redirectioncheck tool from EMMOntoPy:
#
#     pip install EMMOntoPy
#     redirectioncheck expected_redirections.yaml
#
#
# Interactive testing
# -------------------
# Use: https://htaccess.madewithlove.com/
# Paste in: https://github.com/emmo-repo/w3id.org/blob/master/emmo/.htaccess
# Remember to remove the initial "emmo/" in the URL to test.

---
redirections:

  # EMMO levels
  https://w3id.org/emmo/tlo:                            https://raw.githubusercontent.com/emmo-repo/EMMO/master/tlo.ttl
  https://w3id.org/emmo/mlo:                            https://raw.githubusercontent.com/emmo-repo/EMMO/master/mlo.ttl
  https://w3id.org/emmo/foundation:                     https://raw.githubusercontent.com/emmo-repo/EMMO/master/foundation/foundation.ttl
  https://w3id.org/emmo/perspectives:                   https://raw.githubusercontent.com/emmo-repo/EMMO/master/perspectives/perspectives.ttl
  https://w3id.org/emmo/reference:                      https://raw.githubusercontent.com/emmo-repo/EMMO/master/reference/reference.ttl
  https://w3id.org/emmo/disciplines:                    https://raw.githubusercontent.com/emmo-repo/EMMO/master/disciplines/disciplines.ttl

  #https://w3id.org/emmo/1.0.3/tlo:                      https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/tlo.ttl
  #https://w3id.org/emmo/1.0.3/mlo:                      https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/mlo.ttl
  #https://w3id.org/emmo/1.0.3/foundation:               https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/foundation/foundation.ttl
  #https://w3id.org/emmo/1.0.3/perspectives:             https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/perspectives/perspectives.ttl
  #https://w3id.org/emmo/1.0.3/reference:                https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/reference/reference.ttl
  #https://w3id.org/emmo/1.0.3/disciplines:              https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/disciplines/disciplines.ttl

  # Deprecated EMMO levels and modules (forward compatible)
  #https://w3id.org/emmo/mereocausality:                 https://raw.githubusercontent.com/emmo-repo/EMMO/master/foundation/foundation.ttl
  #https://w3id.org/emmo/multiperspective:               https://raw.githubusercontent.com/emmo-repo/EMMO/master/reference/reference.ttl
  https://w3id.org/emmo/1.0.1/mereocausality:           https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.1/mereocausality/mereocausality.ttl
  https://w3id.org/emmo/1.0.0-rc1/multiperspective:     https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-rc1/multiperspective/multiperspective.ttl

  # EMMO modules
  https://w3id.org/emmo/emmo:                           https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  #https://w3id.org/emmo/emax:                           https://raw.githubusercontent.com/emmo-repo/EMMO/master/emax.ttl
  https://w3id.org/emmo/hume/hume:                      https://emmo-repo.github.io/hume/hume.ttl
  https://w3id.org/emmo/elite:                          https://raw.githubusercontent.com/emmo-repo/ELITE/master/elite.ttl
  https://w3id.org/emmo/inferred:                       https://emmo-repo.github.io/emmo-inferred.ttl
  https://w3id.org/emmo/hume/inferred:                  https://emmo-repo.github.io/hume-inferred.ttl

  https://w3id.org/emmo/1.0.2/emmo:                     https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/emmo.ttl
  https://w3id.org/emmo/1.0.2/emax:                     https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/emax.ttl
  https://w3id.org/emmo/1.0.2/hume/hume:                https://emmo-repo.github.io/versions/1.0.2/hume/hume.ttl
  https://w3id.org/emmo/0.0.7/elite:                    https://raw.githubusercontent.com/emmo-repo/ELITE/0.0.7/elite.ttl
  https://w3id.org/emmo/1.0.2/inferred:                 https://emmo-repo.github.io/versions/1.0.2/emmo-inferred.ttl
  https://w3id.org/emmo/1.0.2/hume/inferred:            https://emmo-repo.github.io/versions/1.0.2/hume-inferred.ttl

  https://w3id.org/emmo/reference/data:                 https://raw.githubusercontent.com/emmo-repo/EMMO/master/reference/data.ttl
  https://w3id.org/emmo/1.0.2/reference/data:           https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.2/reference/data.ttl
  https://w3id.org/emmo/hume/reference/data:            https://emmo-repo.github.io/hume/reference/data.ttl
  https://w3id.org/emmo/1.0.2/hume/reference/data:      https://emmo-repo.github.io/versions/1.0.2/hume/reference/data.ttl

  # EMMO namespaces
  https://w3id.org/emmo:                                https://emmo-repo.github.io/emmo.ttl  # ttl file because tests are not from a browser
  https://w3id.org/emmo/hume:                           https://emmo-repo.github.io/hume.ttl  # ttl file because tests are not from a browser
  https://w3id.org/emmo/elite:                          https://w3id.org/emmo/elite

  https://w3id.org/emmo/:                               https://emmo-repo.github.io/emmo.ttl
  https://w3id.org/emmo#fragment:                       https://emmo-repo.github.io/emmo.ttl#fragment  # ttl file because tests are not from a browser
  https://w3id.org/emmo/turtle:                         https://emmo-repo.github.io/emmo.ttl
  https://w3id.org/emmo/turtle/:                        https://emmo-repo.github.io/emmo.ttl
  https://w3id.org/emmo/source:                         https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/source/:                        https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/latest:                         https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/latest/:                        https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/emmo:                           https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/emmo/:                          https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl

  https://w3id.org/emmo/1.0.1:                          https://emmo-repo.github.io/versions/1.0.1/emmo.ttl
  https://w3id.org/emmo/1.0.1/:                         https://emmo-repo.github.io/versions/1.0.1/emmo.ttl
  https://w3id.org/emmo/1.0.0:                          https://emmo-repo.github.io/versions/1.0.0/emmo.ttl
  https://w3id.org/emmo/1.0.0-rc1:                      https://emmo-repo.github.io/versions/1.0.0-rc1/emmo.ttl
  https://w3id.org/emmo/1.0.0-rc1/:                     https://emmo-repo.github.io/versions/1.0.0-rc1/emmo.ttl
  https://w3id.org/emmo/1.0.0-rc1/turtle:               https://emmo-repo.github.io/versions/1.0.0-rc1/emmo.ttl
  https://w3id.org/emmo/1.0.0-rc1/turtle/:              https://emmo-repo.github.io/versions/1.0.0-rc1/emmo.ttl
  https://w3id.org/emmo/1.0.0-beta4:                    https://emmo-repo.github.io/versions/1.0.0-beta4/emmo.ttl



  https://w3id.org/emmo/1.0.0-beta4/inferred:           https://emmo-repo.github.io/versions/1.0.0-beta4/emmo-inferred.ttl
  https://w3id.org/emmo/1.0.0-beta5:                    https://emmo-repo.github.io/versions/1.0.0-beta5/emmo.ttl
  https://w3id.org/emmo/1.0.0-beta5/:                   https://emmo-repo.github.io/versions/1.0.0-beta5/emmo.ttl
  https://w3id.org/emmo/1.0.0-beta5/mereocausality:     https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/mereocausality/mereocausality.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives:       https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/perspectives.ttl
  https://w3id.org/emmo/1.0.0-beta5/multiperspective:   https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/multiperspective/multiperspective.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines:        https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/disciplines.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/units.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/units.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/siunits:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/siunits.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/siunits/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/siunits.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives/data:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/data.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives/data/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/data.ttl


  # EMMO raw
  https://w3id.org/emmo/raw/emmo.ttl:                   https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/raw/emax.ttl:                   https://raw.githubusercontent.com/emmo-repo/EMMO/master/emax.ttl
  https://w3id.org/emmo/raw/disciplines/isq.ttl:        https://raw.githubusercontent.com/emmo-repo/EMMO/master/disciplines/isq.ttl
##  https://w3id.org/emmo/raw/dev/doc/emmo-logo.ttl:      https://raw.githubusercontent.com/emmo-repo/EMMO/master/dev/doc/emmo-logo.ttl
##  https://w3id.org/emmo/raw/dev/emmo-full.ttl:          https://raw.githubusercontent.com/emmo-repo/EMMO/dev/emmo-full.ttl
##  https://w3id.org/emmo/raw/dev/disciplines/isq.ttl:    https://raw.githubusercontent.com/emmo-repo/EMMO/dev/disciplines/isq.ttl
  https://w3id.org/emmo/raw/1.0.0/disciplines/isq.ttl:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0/disciplines/isq.ttl


  # EMMO-LITE
  https://w3id.org/emmo/elite:                      https://raw.githubusercontent.com/emmo-repo/ELITE/master/elite.ttl
  #https://w3id.org/emmo/1.0.1/elite:            https://raw.githubusercontent.com/emmo-repo/EMMO-LITE/1.0.1/elite.ttl


  # Electrochemistry
  #https://w3id.org/emmo/domain/electrochemistry#frag:   https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl#frag

  #https://w3id.org/emmo/domain/electrochemistry:        https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl
  #https://w3id.org/emmo/domain/electrochemistry/:       https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl
  https://w3id.org/emmo/domain/electrochemistry/source: https://raw.githubusercontent.com/emmo-repo/domain-electrochemistry/master/electrochemistry.ttl
  https://w3id.org/emmo/domain/electrochemistry/electrochemistry: https://raw.githubusercontent.com/emmo-repo/domain-electrochemistry/master/electrochemistry.ttl


  # Battery
  #https://w3id.org/emmo/domain/battery#fragment:        https://emmo-repo.github.io/domain-battery/battery.ttl#fragment

  #https://w3id.org/emmo/domain/battery:                 https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/battery/:                https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/domain-battery:          https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/domain-battery/:         https://emmo-repo.github.io/domain-battery/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/source:   https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/source/:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/latest:   https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/latest/:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/battery:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/battery/: https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/source:          https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/source/:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/latest:          https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/latest/:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/battery:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/battery/:        https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl


  # Context
  https://w3id.org/emmo/domain/domain-electrochemistry/context:       https://emmo-repo.github.io/domain-electrochemistry/context/context.json
  https://w3id.org/emmo/domain/domain-electrochemistry/context/:      https://emmo-repo.github.io/domain-electrochemistry/context/context.json
  #https://w3id.org/emmo/domain/domain-battery/context/abc:            https://emmo-repo.github.io/domain-battery/context/context/abc.json
  #https://w3id.org/emmo/domain/domain-battery/context/abc/:           https://emmo-repo.github.io/domain-battery/context/context/abc.json


  # Microstructure
  https://w3id.org/emmo/domain/domain-microstructure/source:   https://raw.githubusercontent.com/emmo-repo/domain-microstructure/master/microstructure.ttl
  https://w3id.org/emmo/domain/domain-microstructure:          https://emmo-repo.github.io/domain-microstructure/microstructure.ttl
  https://w3id.org/emmo/domain/microstructure/source:          https://raw.githubusercontent.com/emmo-repo/domain-microstructure/master/microstructure.ttl
  https://w3id.org/emmo/domain/microstructure:                 https://emmo-repo.github.io/domain-microstructure/microstructure.ttl


  # application-battmo
  https://w3id.org/emmo/application/battmo/source:             https://raw.githubusercontent.com/emmo-repo/application-battmo/master/battmo.ttl


  # Coating
  https://w3id.org/emmo/domain/coating:                        https://emmo-repo.github.io/domain-coating/coating.ttl


  # CHAMEO
  #https://w3id.org/emmo/domain/characterisation-methodology/chameo:             https://emmo-repo.github.io/domain-characterisation-methodology/chameo.ttl
  #https://w3id.org/emmo/domain/characterisation-methodology/chameo#:            https://emmo-repo.github.io/domain-characterisation-methodology/chameo.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/inferred:    https://emmo-repo.github.io/domain-characterisation-methodology/chameo-inferred.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/turtle:      https://emmo-repo.github.io/domain-characterisation-methodology/chameo.ttl
  #https://w3id.org/emmo/domain/characterisation-methodology/chameo/context:     https://emmo-repo.github.io/domain-characterisation-methodology/context/chameo.json
  #https://w3id.org/emmo/domain/characterisation-methodology/chameo/context/ch:  https://emmo-repo.github.io/domain-characterisation-methodology/context/ch.json

  #https://w3id.org/emmo/domain/characterisation-methodology/chameo/:            https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/master/chameo.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/latest:      https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/master/chameo.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/latest/:     https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/master/chameo.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/source:      https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/master/chameo.ttl
  https://w3id.org/emmo/domain/characterisation-methodology/chameo/source/:     https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/master/chameo.ttl

  #https://w3id.org/emmo/domain/characterisation-methodology/chameo/1.0.0-beta3: https://emmo-repo.github.io/domain-characterisation-methodology/versions/1.0.0-beta3/chameo.ttl

  https://w3id.org/emmo/domain/characterisation-methodology/chameo/1.0.0-beta3/source:  https://raw.githubusercontent.com/emmo-repo/domain-characterisation-methodology/1.0.0-beta3/chameo.ttl
