# Input file for testing redirections
#
# These redirections can be tested using the redirectioncheck tool from EMMOntoPy:
#
#     pip install EMMOntoPy
#     redirectioncheck expected_redirections.yaml
#

---
redirections:

  # EMMO
  https://w3id.org/emmo#fragment:                       https://emmo-repo.github.io/emmo.ttl#fragment  # ttl file because tests are not from a browser

  https://w3id.org/emmo:                                https://emmo-repo.github.io/emmo.ttl  # ttl file because tests are not from a browser
  https://w3id.org/emmo/:                               https://emmo-repo.github.io/emmo.ttl
  https://w3id.org/emmo/inferred:                       https://emmo-repo.github.io/emmo-inferred.ttl
  https://w3id.org/emmo/1.0.0-beta4:                    https://emmo-repo.github.io/versions/1.0.0-beta4/emmo.ttl
  https://w3id.org/emmo/1.0.0-beta4/inferred:           https://emmo-repo.github.io/versions/1.0.0-beta4/emmo-inferred.ttl
  https://w3id.org/emmo/1.0.0-beta5:                    https://emmo-repo.github.io/versions/1.0.0-beta5/emmo.ttl
  https://w3id.org/emmo/1.0.0-beta5/:                   https://emmo-repo.github.io/versions/1.0.0-beta5/emmo.ttl

  https://w3id.org/emmo/source:                         https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/source/:                        https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/latest:                         https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/latest/:                        https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/emmo:                           https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  https://w3id.org/emmo/emmo/:                          https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo.ttl
  #https://w3id.org/emmo/disciplines:                    https://raw.githubusercontent.com/emmo-repo/EMMO/master/disciplines/disciplines.ttl  # not in master
  https://w3id.org/emmo/1.0.0-beta5/mereocausality:     https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/mereocausality/mereocausality.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives:       https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/perspectives.ttl
  https://w3id.org/emmo/1.0.0-beta5/multiperspective:   https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/multiperspective/multiperspective.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines:        https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/disciplines.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/units.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/units.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/siunits:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/siunits.ttl
  https://w3id.org/emmo/1.0.0-beta5/disciplines/units/siunits/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/disciplines/units/siunits.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives/data:  https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/data.ttl
  https://w3id.org/emmo/1.0.0-beta5/perspectives/data/: https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta5/perspectives/data.ttl


  # Electrochemistry
  #https://w3id.org/emmo/domain/electrochemistry#frag:   https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl#frag

  #https://w3id.org/emmo/domain/electrochemistry:        https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl
  #https://w3id.org/emmo/domain/electrochemistry/:       https://emmo-repo.github.io/domain-electrochemistry/electrochemistry.ttl
  https://w3id.org/emmo/domain/electrochemistry/source: https://raw.githubusercontent.com/emmo-repo/domain-electrochemistry/master/electrochemistry.ttl
  https://w3id.org/emmo/domain/electrochemistry/electrochemistry: https://raw.githubusercontent.com/emmo-repo/domain-electrochemistry/master/electrochemistry.ttl


  # Battery
  #https://w3id.org/emmo/domain/battery#fragment:        https://emmo-repo.github.io/domain-battery/battery.ttl#fragment

  #https://w3id.org/emmo/domain/battery:                 https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/battery/:                https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/domain-battery:          https://emmo-repo.github.io/domain-battery/battery.ttl
  #https://w3id.org/emmo/domain/domain-battery/:         https://emmo-repo.github.io/domain-battery/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/source:   https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/source/:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/latest:   https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/latest/:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/battery:  https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/domain-battery/battery/: https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/source:          https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/source/:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/latest:          https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/latest/:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/battery:         https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl
  https://w3id.org/emmo/domain/battery/battery/:        https://raw.githubusercontent.com/emmo-repo/domain-battery/master/battery.ttl


  # Context
  https://w3id.org/emmo/domain/domain-electrochemistry/context:       https://emmo-repo.github.io/domain-electrochemistry/context/context.json
  https://w3id.org/emmo/domain/domain-electrochemistry/context/:      https://emmo-repo.github.io/domain-electrochemistry/context/context.json
  #https://w3id.org/emmo/domain/domain-battery/context/abc:            https://emmo-repo.github.io/domain-battery/context/context/abc.json
  #https://w3id.org/emmo/domain/domain-battery/context/abc/:           https://emmo-repo.github.io/domain-battery/context/context/abc.json


  # Microstructure
  https://w3id.org/emmo/domain/domain-microstructure/source:   https://raw.githubusercontent.com/emmo-repo/domain-microstructure/master/microstructure.ttl
  https://w3id.org/emmo/domain/domain-microstructure:          https://emmo-repo.github.io/domain-microstructure/microstructure.ttl
  https://w3id.org/emmo/domain/microstructure/source:          https://raw.githubusercontent.com/emmo-repo/domain-microstructure/master/microstructure.ttl
  https://w3id.org/emmo/domain/microstructure:                 https://emmo-repo.github.io/domain-microstructure/microstructure.ttl
