name: Release to GitHub Pages

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Release to GitHub Pages
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${SSH_PRIVATE_KEY}"
        git config --global user.email "emmo.github.action@github.com"
        git config --global user.name "EMMO GitHub Action"
        .github/mkrelease.sh
